name: Build HTML from Markdown

on:
  workflow_dispatch:
  push:
    branches: [ "site" ]
  workflow_run:
    workflows: [ Merge ]
    types: [ completed ]
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout to site branch
        run: git switch site

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py to generate HTML
        run: python main.py

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add docs/
          git diff --staged --quiet || git commit -m "Auto-generate HTML from Markdown files"
          git push
