name: Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rebase-quartz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge main into site
        run: |
          git switch site
          git merge origin/main --no-edit

      - name: Push rebased site
        run: |
          git push --force